config/routes.rb
NonProfit::Application.routes.draw do
  root to: 'nonprofits#index'
  resources :nonprofits do
    resources :charges
  end
end

app/models/nonprofit.rb
class Nonprofit < ActiveRecord::Base
  validates :name, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
end

app/controllers/charges_controller.rb
class ChargesController < ApplicationController
  def new
    @nonprofit = Nonprofit.find(params[:nonprofit_id])
  end

  def create



# Set your secret key: remember to change this to your live secret key in production
# See your keys here https://manage.stripe.com/account
Stripe.api_key = "sk_test_SewUriofu2nYsMNOgpklMT9t"

# Get the credit card details submitted by the form
token = params[:stripeToken]
amount = params[:amount].to_i * 100
# Create the charge on Stripe's servers - this will charge the user's card
begin

  charge = Stripe::Charge.create(
    :amount => amount, # amount in cents, again
    :currency => "usd",
    :card => token,
    :description => "payinguser@example.com"
  )
  redirect_to root_path
rescue Stripe::CardError => e
  # The card has been declined
end



  end
end

app/controllers/nonprofits_controller.rb
class NonprofitsController < ApplicationController
  def index
    @nonprofits = Nonprofit.all
  end

  def new
    @nonprofit = Nonprofit.new
  end

  def create
    @nonprofit = Nonprofit.new(nonprofit_params)
    if @nonprofit.save
      respond_to do |format|
        format.html { redirect_to nonprofits_path }
        format.js
      end
    else
      render 'new'
    end
  end

  def show
    @nonprofit = Nonprofit.find(params[:id])
  end

  def destroy
    @nonprofit = Nonprofit.find(params[:id])
    @nonprofit.destroy
    redirect_to root_url
  end

private
  def nonprofit_params
    params.require(:nonprofit).permit(:name, :description)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/charges/_form.html.erb
<div class="stripe-form">
  <form action="" method="POST" id="payment-form" date-remote="true">
    <span class="payment-errors"></span>

    <div class="form-row">
      <label>
        <span>Card Number</span>
        <input type="text" size="20" data-stripe="number"/>
      </label>
    </div>

    <div class="form-row">
      <label>
        <span>CVC</span>
        <input type="text" size="4" data-stripe="cvc"/>
      </label>
    </div>

    <div class="form-row">
      <label>
        <span>Expiration (MM/YYYY)</span>
        <input type="text" size="2" data-stripe="exp-month"/>
      </label>
      <span> / </span>
      <input type="text" size="4" data-stripe="exp-year"/>
    </div>

    <button type="submit">Submit Payment</button>
  </form>
</div>

app/views/charges/new.js.erb
$('#donate-link').hide().after("<%= j render('layouts/stripeform') %>");

app/views/layouts/_errors.html.erb
<% if object.errors.any? %>
  <h3>Error's present:</h3>
  <ul>
    <% object.errors.full_messages.each do |message| %>
    <li><%= message %></li>
    <% end %>
  </ul>
<% end %>

app/views/layouts/_stripeform.html.erb
<div class="stripe-form">
  <form action="/nonprofits/<%= "#{@nonprofit.id}" %>/charges" method="POST" id="payment-form" date-remote="true">
    <span class="payment-errors"></span>

    <div class="form-row">
      <label>
        <span>Amount</span>
        <input type="text" size="8" name="amount" data-stripe="amount"/>
      </label>
    </div>

    <div class="form-row">
      <label>
        <span>Card Number</span>
        <input type="text" size="20" value="4242424242424242" data-stripe="number"/>
      </label>
    </div>

    <div class="form-row">
      <label>
        <span>CVC</span>
        <input type="text" size="4" value="343" data-stripe="cvc"/>
      </label>
    </div>

    <div class="form-row">
      <label>
        <span>Expiration (MM/YYYY)</span>
        <input type="text" size="2" value="12" data-stripe="exp-month"/>
      </label>
      <span> / </span>
      <input type="text" size="4" value="2016" data-stripe="exp-year"/>
    </div>

    <button type="submit">Submit Payment</button>
  </form>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>NonProfit</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
  <script type="text/javascript" src="https://js.stripe.com/v2/"></script>
  <script type="text/javascript">
    // This identifies your website in the createToken call below
    Stripe.setPublishableKey('pk_test_bayibWuxCSwTZ5MwUMjqRod7');

    var stripeResponseHandler = function(status, response) {
      var $form = $('#payment-form');

      if (response.error) {
        // Show the errors on the form
        $form.find('.payment-errors').text(response.error.message);
        $form.find('button').prop('disabled', false);
      } else {
        // token contains id, last4, and card type
        var token = response.id;
        // Insert the token into the form so it gets submitted to the server
        $form.append($('<input type="hidden" name="stripeToken" />').val(token));
        // and re-submit
        $form.get(0).submit();
      }
    };

    jQuery(function($) {
      $('#payment-form').submit(function(e) {
        var $form = $(this);

        // Disable the submit button to prevent repeated clicks
        $form.find('button').prop('disabled', true);

        Stripe.card.createToken($form, stripeResponseHandler);

        // Prevent the form from submitting with the default action
        return false;
      });
    });
  </script>

</head>
<body>
<%= flash[:alert] %>
<%= flash[:notice] %>

<%= yield %>

</body>
</html>

app/views/nonprofits/_form.html.erb
<%= form_for @nonprofit, remote: true, id: 'nonprofit-form' do |f| %>
<%= render('layouts/errors', :object => @nonprofit) %>

<%= f.label :name %>
<%= f.text_field :name %><br>

<%= f.label :description %>
<%= f.text_area :description %><br>

<%= f.submit 'Submit', id: 'nonprofit-submit' %><br>
<%= link_to "Back", root_url %>
<% end %>

app/views/nonprofits/create.js.erb
$('form').hide()
$('.add-link').show()
$('.nonprofits-list').show()

app/views/nonprofits/index.html.erb
<h2>Nonprofits</h2>
<div class="add-link">
  <%= link_to 'Add nonprofit', new_nonprofit_path, id: 'new_nonprofit', remote: true %>
</div>
<div class="nonprofits-list">
  <br>
  <% Nonprofit.all.each do |nonprofit| %>
  <%= link_to nonprofit.name, nonprofit_path(nonprofit) %><br>
  <% end %>
</div>

app/views/nonprofits/new.html.erb
<%= render('form') %>

app/views/nonprofits/new.js.erb
$('#new_nonprofit').hide()
$('.nonprofits-list').hide().after("<%= j render('form') %>");

app/views/nonprofits/show.html.erb
<h2><%= @nonprofit.name %></h2>
<p><%= @nonprofit.description %></p>
<%= button_to "Delete this nonprofit", nonprofit_path, :method => :delete %>
<br>
<%= link_to "Donate", new_charge_path, id: 'donate-link', remote: true %>
<br>
<%= link_to "Home", root_url %>